name: .NET Docker CI

on:
  push:
    paths:
    - 'src/BlazorMyBankAccount/**'
    - '!.github/workflows/**'
    - '!README.md'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build image
        run: docker build --file ./src/githubaction-dockerfile --tag anthonyryck/mybankaccount:latest .
      - name: Push to DockerHub
        run: docker push anthonyryck/mybankaccount:latest
